# Generated by Django 5.0.3 on 2024-04-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name_id',
            new_name='slug',
        ),
    ]
