# Generated by Django 5.0.3 on 2024-05-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rating_answers',
            field=models.BigIntegerField(default=0),
        ),
    ]
