# Generated by Django 5.0.3 on 2024-05-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_rating_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='rating_questions',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_answers',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_questions',
            field=models.BigIntegerField(default=0),
        ),
    ]
