# Generated by Django 5.0.3 on 2024-05-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tag_bootstrap_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='bootstrap_icon',
            field=models.CharField(max_length=100),
        ),
    ]
