# Generated by Django 5.0.3 on 2024-05-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_path',
            field=models.ImageField(max_length=300, upload_to=''),
        ),
    ]
