# Generated by Django 5.0.3 on 2024-05-29 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_question_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='image_path',
            new_name='image',
        ),
    ]
